### spring配置
spring:
  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.103:9020/mddb?useSSL=false&characterEncoding=utf-8
#    url: jdbc:mysql://127.0.0.1:3306/timo?useSSL=false&characterEncoding=utf-8
    username: root
    password: Passw0rd